/** AUTO-GENERATED by scripts/extract-characters.mjs — per-character actions
 * salvaged from the original Flash SWFs. Do not edit by hand. */
export type CharAction = 'idle' | 'talk' | 'joy' | 'sad' | 'angry' | 'jump';
export const CHARACTER_ACTIONS: Record<string, CharAction[]> = {
  "anaboushi": [
    "idle",
    "talk"
  ],
  "ashinaga": [
    "idle",
    "talk",
    "joy",
    "angry"
  ],
  "binzume": [
    "idle",
    "talk"
  ],
  "bonbori": [
    "idle",
    "talk"
  ],
  "bousan": [
    "idle",
    "talk"
  ],
  "chazutsu": [
    "idle",
    "talk"
  ],
  "daifuku": [
    "idle",
    "talk",
    "joy",
    "sad",
    "angry",
    "jump"
  ],
  "enbou": [
    "idle",
    "talk",
    "joy",
    "sad",
    "angry",
    "jump"
  ],
  "fudousan": [
    "idle",
    "talk",
    "joy"
  ],
  "fusen": [
    "idle",
    "talk"
  ],
  "fuurinn": [
    "idle",
    "talk"
  ],
  "ganbunsan": [
    "idle",
    "talk",
    "joy"
  ],
  "hanedama": [
    "idle",
    "talk"
  ],
  "inanaki": [
    "idle",
    "talk"
  ],
  "iwakurage": [
    "idle",
    "talk"
  ],
  "muda": [
    "idle",
    "talk"
  ],
  "nageki": [
    "idle",
    "talk"
  ],
  "nagi": [
    "idle",
    "talk"
  ],
  "nasu": [
    "idle",
    "talk",
    "sad",
    "angry"
  ],
  "nuronuro": [
    "idle",
    "talk"
  ],
  "okekamuri": [
    "idle",
    "talk"
  ],
  "semi": [
    "idle",
    "talk"
  ],
  "sinatora": [
    "idle",
    "talk"
  ],
  "teme": [
    "idle",
    "talk"
  ],
  "tofu": [
    "idle",
    "talk"
  ],
  "tokkuri": [
    "idle",
    "talk"
  ],
  "toudai": [
    "idle",
    "talk"
  ],
  "toukaduki": [
    "idle",
    "talk"
  ],
  "tsurigane": [
    "idle",
    "talk"
  ],
  "uragawa": [
    "idle",
    "talk"
  ],
  "warabi": [
    "idle",
    "talk"
  ],
  "yotsude": [
    "idle",
    "talk"
  ],
  "yuragi": [
    "idle",
    "talk"
  ]
};

/** Extra per-character animations also salvaged from the SWFs — alternate
 * idles/lip-talks (idle2/talk2/idle3/talk3) and creature-specific flourishes
 * (berori, chonmage, furiko, spin, memo, …). Each has a GIF at
 * public/characters/{id}_{extra}.gif. Not yet wired into gameplay states;
 * available for future use (e.g. idle variety, reactions). */
export const CHARACTER_EXTRA_ACTIONS: Record<string, string[]> = {
  "anaboushi": [
    "idle2",
    "talk2"
  ],
  "ashinaga": [],
  "binzume": [
    "idle2",
    "talk2",
    "idle3",
    "talk3"
  ],
  "bonbori": [],
  "bousan": [],
  "chazutsu": [
    "idle2",
    "talk2"
  ],
  "daifuku": [
    "idle2",
    "talk2",
    "berori",
    "chonmage",
    "furiko"
  ],
  "enbou": [
    "spin"
  ],
  "fudousan": [
    "idle2",
    "talk2",
    "idle3",
    "talk3",
    "memo"
  ],
  "fusen": [],
  "fuurinn": [
    "idle2",
    "talk2"
  ],
  "ganbunsan": [],
  "hanedama": [],
  "inanaki": [],
  "iwakurage": [],
  "muda": [],
  "nageki": [],
  "nagi": [],
  "nasu": [],
  "nuronuro": [],
  "okekamuri": [
    "idle2",
    "talk2"
  ],
  "semi": [],
  "sinatora": [],
  "teme": [
    "miru"
  ],
  "tofu": [
    "idle2",
    "talk2"
  ],
  "tokkuri": [],
  "toudai": [],
  "toukaduki": [],
  "tsurigane": [
    "idle2",
    "talk2"
  ],
  "uragawa": [],
  "warabi": [],
  "yotsude": [
    "idle2",
    "talk2",
    "idle3",
    "talk3"
  ],
  "yuragi": []
};
