/** AUTO-GENERATED by .tools/extract-characters.mjs — per-character actions
 * salvaged from the original Flash SWFs. Do not edit by hand. */
export type CharAction = 'idle' | 'talk' | 'joy' | 'sad' | 'angry' | 'jump';
export const CHARACTER_ACTIONS: Record<string, CharAction[]> = {
  "anaboushi": [
    "idle",
    "talk"
  ],
  "ashinaga": [
    "idle",
    "talk",
    "joy",
    "angry"
  ],
  "binzume": [
    "idle",
    "talk"
  ],
  "bonbori": [
    "idle",
    "talk"
  ],
  "bousan": [
    "idle",
    "talk"
  ],
  "chazutsu": [
    "idle",
    "talk"
  ],
  "daifuku": [
    "idle",
    "talk",
    "joy",
    "sad",
    "angry",
    "jump"
  ],
  "enbou": [
    "idle",
    "talk",
    "joy",
    "sad",
    "angry"
  ],
  "fudousan": [
    "idle",
    "talk",
    "joy"
  ],
  "fusen": [
    "idle",
    "talk"
  ],
  "fuurinn": [
    "idle",
    "talk"
  ],
  "ganbunsan": [
    "idle",
    "talk",
    "joy"
  ],
  "hanedama": [
    "idle",
    "talk"
  ],
  "inanaki": [
    "idle",
    "talk"
  ],
  "iwakurage": [
    "idle",
    "talk"
  ],
  "muda": [
    "idle",
    "talk"
  ],
  "nageki": [
    "idle",
    "talk"
  ],
  "nagi": [
    "idle",
    "talk"
  ],
  "nasu": [
    "idle",
    "talk",
    "sad",
    "angry"
  ],
  "nuronuro": [
    "idle",
    "talk"
  ],
  "okekamuri": [
    "idle",
    "talk"
  ],
  "semi": [
    "idle",
    "talk"
  ],
  "sinatora": [
    "idle",
    "talk"
  ],
  "teme": [
    "idle",
    "talk"
  ],
  "tofu": [
    "idle",
    "talk"
  ],
  "tokkuri": [
    "idle",
    "talk"
  ],
  "toudai": [
    "idle",
    "talk"
  ],
  "toukaduki": [
    "idle",
    "talk"
  ],
  "tsurigane": [
    "idle",
    "talk"
  ],
  "uragawa": [
    "idle",
    "talk"
  ],
  "warabi": [
    "idle",
    "talk"
  ],
  "yotsude": [
    "idle",
    "talk"
  ],
  "yuragi": [
    "idle",
    "talk"
  ]
};
