/**
 * roomItems - Original room-decoration furniture salvaged from the archive's
 * `visual/room/*.png` set. The old Flash game treated the room as a place where
 * tiny personal objects accumulate; keep that density by exposing the original
 * item PNGs, while preserving the short legacy ids already used by saves/tests.
 */

import { ASSET_BASE } from '../assetBase';

export interface RoomItemDef {
  id: string;
  /** display name (hiragana/katakana) */
  name: string;
  /** served path to the pixel-art sprite */
  art: string;
}

const ORIGINAL_ITEM_FILES = [
  'item_000_iryogoods.png',
  'item_000_isu.png',
  'item_000_karute.png',
  'item_000_tana.png',
  'item_001_denshirenji.png',
  'item_001_kine.png',
  'item_001_mochi.png',
  'item_001_mushikago.png',
  'item_001_torikago.png',
  'item_001_usu.png',
  'item_002_akibin.png',
  'item_002_akikan.png',
  'item_002_album.png',
  'item_002_gomibukuro.png',
  'item_002_nuigurumi.png',
  'item_002_okashi.png',
  'item_002_sentakumono.png',
  'item_002_tishu.png',
  'item_003_epron.png',
  'item_003_furaikaeshi.png',
  'item_003_furaipan.png',
  'item_003_fuusha.png',
  'item_003_kaneshon.png',
  'item_003_nabetsukami.png',
  'item_003_senzai.png',
  'item_003_suponji.png',
  'item_004_DJ.png',
  'item_004_asago.png',
  'item_004_jyoro.png',
  'item_004_kanyoshokubutu.png',
  'item_004_record.png',
  'item_004_sukoppu.png',
  'item_005_butuzou.png',
  'item_005_gojyunotou.png',
  'item_005_karetahana.png',
  'item_005_kinkakuji.png',
  'item_005_omamori.png',
  'item_005_otabe.png',
  'item_005_panfuretto.png',
  'item_005_yunomi.png',
  'item_006_bodysorp.png',
  'item_006_rinsu.png',
  'item_006_senmenki.png',
  'item_006_shanpu.png',
  'item_006_shawahead.png',
  'item_006_taoru.png',
  'item_007_C.png',
  'item_007_kutsu.png',
  'item_007_kutsubako.png',
  'item_007_megane.png',
  'item_007_megusuri.png',
  'item_007_tsukemastuge.png',
  'item_008_akibin.png',
  'item_008_lamp.png',
  'item_008_orange.png',
  'item_008_reizouko.png',
  'item_008_tokei.png',
  'item_009_closet.png',
  'item_009_hanger.png',
  'item_009_onepeice.png',
  'item_009_shasin.png',
  'item_009_skirf.png',
  'item_010_denwa.png',
  'item_010_hako.png',
  'item_010_kagami.png',
  'item_010_kousui.png',
  'item_010_supurei.png',
  'item_011_Tshirt.png',
  'item_011_benkyo.png',
  'item_011_enpitsu.png',
  'item_011_fukuro.png',
  'item_011_hondana.png',
  'item_011_jisho.png',
  'item_011_kyokasho.png',
  'item_011_note.png',
  'item_012_chousinki.png',
  'item_012_hasami.png',
  'item_012_houtai.png',
  'item_012_kusuri.png',
  'item_012_kusuribako.png',
  'item_013_chawan.png',
  'item_013_fuku.png',
  'item_013_kutsushita.png',
  'item_013_saikoro.png',
  'item_013_tokei.png',
  'item_014_TV.png',
  'item_014_aircon.png',
  'item_014_stereo.png',
  'item_014_tana.png',
  'item_014_video.png',
  'item_015_camera.png',
  'item_015_denchi.png',
  'item_015_lef.png',
  'item_015_light.png',
  'item_015_printer.png',
  'item_017_cap.png',
  'item_017_cup.png',
  'item_017_haburashi.png',
  'item_017_handcream.png',
  'item_017_kamibukuro.png',
  'item_017_tebukuro.png',
  'item_019_gomibako.png',
  'item_019_magazinebox.png',
  'item_019_manga.png',
  'item_019_tessues.png',
  'item_019_zasshi.png',
] as const;

const NAME_BY_KEY: Record<string, string> = {
  aircon: 'エアコン',
  akibin: 'あきびん',
  akikan: 'あきかん',
  album: 'アルバム',
  asago: 'あさがお',
  benkyo: 'べんきょう机',
  bodysorp: 'ボディソープ',
  butuzou: 'ぶつぞう',
  camera: 'カメラ',
  cap: 'ぼうし',
  chawan: 'ちゃわん',
  chousinki: 'ちょうしんき',
  closet: 'クローゼット',
  cup: 'コップ',
  denchi: 'でんち',
  denshirenji: 'でんしレンジ',
  denwa: 'でんわ',
  DJ: 'DJセット',
  enpitsu: 'えんぴつ',
  epron: 'エプロン',
  fuku: 'ふく',
  fukuro: 'ふくろ',
  furaikaeshi: 'フライがえし',
  furaipan: 'フライパン',
  fuusha: 'ふうしゃ',
  gojyunotou: 'ごじゅうのとう',
  gomibako: 'ごみばこ',
  gomibukuro: 'ごみぶくろ',
  haburashi: 'はぶらし',
  hako: 'はこ',
  handcream: 'ハンドクリーム',
  hanger: 'ハンガー',
  hasami: 'はさみ',
  hondana: 'ほんだな',
  houtai: 'ほうたい',
  iryogoods: 'いりょうグッズ',
  isu: 'いす',
  jisho: 'じしょ',
  jyoro: 'じょうろ',
  kagami: 'かがみ',
  kamibukuro: 'かみぶくろ',
  kaneshon: 'カーネーション',
  karte: 'カルテ',
  karute: 'カルテ',
  karetahana: 'かれたはな',
  kanyoshokubutu: 'かんよう植物',
  kinkakuji: 'きんかくじ',
  kine: 'きね',
  kousui: 'こうすい',
  kusuri: 'くすり',
  kusuribako: 'くすりばこ',
  kutsu: 'くつ',
  kutsubako: 'くつばこ',
  kutsushita: 'くつした',
  kyokasho: 'きょうかしょ',
  lamp: 'ランプ',
  lef: 'つくえライト',
  light: 'ライト',
  magazinebox: 'マガジンラック',
  manga: 'マンガ',
  megane: 'めがね',
  megusuri: 'めぐすり',
  mochi: 'もち',
  mushikago: 'むしかご',
  nabetsukami: 'なべつかみ',
  note: 'ノート',
  nuigurumi: 'ぬいぐるみ',
  okashi: 'おかし',
  omamori: 'おまもり',
  onepeice: 'ワンピース',
  orange: 'オレンジ',
  otabe: 'おたべ',
  panfuretto: 'パンフレット',
  printer: 'プリンター',
  record: 'レコード',
  reizouko: 'れいぞうこ',
  rinsu: 'リンス',
  saikoro: 'サイコロ',
  senmenki: 'せんめんき',
  sentakumono: 'せんたくもの',
  senzai: 'せんざい',
  shanpu: 'シャンプー',
  shasin: 'しゃしん',
  shawahead: 'シャワーヘッド',
  skirf: 'スカーフ',
  stereo: 'ステレオ',
  sukoppu: 'スコップ',
  suponji: 'スポンジ',
  supurei: 'スプレー',
  tana: 'たな',
  taoru: 'タオル',
  tebukuro: 'てぶくろ',
  tessues: 'ティッシュ',
  tishu: 'ティッシュ',
  tokei: 'とけい',
  torikago: 'とりかご',
  tsukemastuge: 'つけまつげ',
  TV: 'テレビ',
  usu: 'うす',
  video: 'ビデオ',
  zasshi: 'ざっし',
};

const LEGACY_ITEMS: Array<[id: string, name: string, file: string]> = [
  ['tv', 'テレビ', 'item_014_TV.png'],
  ['stereo', 'ステレオ', 'item_014_stereo.png'],
  ['video', 'ビデオ', 'item_014_video.png'],
  ['aircon', 'エアコン', 'item_014_aircon.png'],
  ['shelf', 'たな', 'item_014_tana.png'],
  ['clock', 'とけい', 'item_013_tokei.png'],
  ['light', 'ライト', 'item_015_light.png'],
  ['camera', 'カメラ', 'item_015_camera.png'],
  ['chair', 'いす', 'item_000_isu.png'],
  ['record', 'レコード', 'item_004_record.png'],
  ['plant', 'かんよう植物', 'item_004_kanyoshokubutu.png'],
  ['plushie', 'ぬいぐるみ', 'item_002_nuigurumi.png'],
  ['birdcage', 'とりかご', 'item_001_torikago.png'],
  ['towel', 'タオル', 'item_006_taoru.png'],
  ['charm', 'おまもり', 'item_005_omamori.png'],
  ['microwave', 'でんしレンジ', 'item_001_denshirenji.png'],
];

const originalItems = ORIGINAL_ITEM_FILES.map((file) => {
  const id = file.replace(/\.png$/, '');
  return makeItem(id, nameFor(id), file);
});

const legacyItems = LEGACY_ITEMS.map(([id, name, file]) => makeItem(id, name, file));

export const ROOM_ITEMS: readonly RoomItemDef[] = [...legacyItems, ...originalItems];

export const ROOM_ITEM_IDS: readonly string[] = ROOM_ITEMS.map((i) => i.id);

const BY_ID = new Map(ROOM_ITEMS.map((i) => [i.id, i]));

export function getRoomItem(id: string): RoomItemDef | undefined {
  return BY_ID.get(id);
}

/** A fuller starter set so the reconstructed room editor behaves like the old
 *  app's "自分の部屋" inventory shelf instead of a tiny prototype palette. */
export const STARTER_ITEM_IDS: readonly string[] = [
  'chair',
  'clock',
  'plushie',
  'plant',
  'light',
  'item_000_tana',
  'item_009_closet',
  'item_011_hondana',
  'item_008_reizouko',
  'item_014_TV',
  'item_014_stereo',
  'item_010_denwa',
  'item_012_kusuribako',
  'item_019_zasshi',
  'item_005_omamori',
  'item_007_kutsu',
];

function makeItem(id: string, name: string, file: string): RoomItemDef {
  return { id, name, art: `${ASSET_BASE}assets/room-items/${file}` };
}

function nameFor(id: string): string {
  const key = id.replace(/^item_\d+_/, '');
  return NAME_BY_KEY[key] ?? key;
}
